/**
 * Analysis size limits (same for every plan — they protect the worker,
 * not a billing tier).
 */
export const MAX_REPO_SIZE_BYTES = 100 * 1024 * 1024; // 100 MB
/**
 * A ZIP sent through the browser: Vercel caps a function's request body at
 * 4.5 MB, so a bigger upload never reaches the app (TD-45, ADR-011). 4 MB
 * leaves room for the multipart envelope. Bigger projects come from GitHub
 * (downloaded by the job, up to MAX_REPO_SIZE_BYTES).
 */
export const MAX_UPLOAD_BYTES = 4 * 1024 * 1024;
export const UPLOAD_TOO_BIG_MESSAGE =
  "ZIP uploads are limited to 4 MB. For a bigger project, import it from GitHub.";
/** JS/TS files per repository (the files that are read and analyzed). */
export const MAX_FILE_COUNT = 1000;
export const MAX_FILE_SIZE_BYTES = 500 * 1024; // 500 KB
/** The root npm lockfile, read for the dependency scan and never stored (ADR-012). */
export const MAX_LOCKFILE_BYTES = 10 * 1024 * 1024; // 10 MB
/** Raw ZIP entries (before filtering); bounds work on hostile archives. */
export const MAX_ZIP_ENTRIES = 50_000;

/** RAG retrieval size */
export const RAG_TOP_K = 8;

/** Characters of a file sent to the model by "Explain this file" (the rest is cut). */
export const EXPLAIN_MAX_CHARS = 12_000;

/** Source file extensions that are parsed and chunked */
export const SOURCE_EXTENSIONS = new Set([".js", ".jsx", ".ts", ".tsx"]);

/** Always-excluded path segments / filenames */
export const ALWAYS_EXCLUDE_DIR_NAMES = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  "coverage",
  ".turbo",
  ".vercel",
  ".data",
  // Generated by other frameworks and tools (build output and caches).
  ".nuxt",
  ".output",
  ".svelte-kit",
  ".docusaurus",
  ".expo",
  ".cache",
  ".parcel-cache",
  ".yarn",
  // Third-party code copied into the repository: not the project's code, and
  // it takes the review sample and yields findings about someone else's code.
  // (`vendor` is also a domain word: see VENDOR_DIR_NAME.)
  "third_party",
  "third-party",
  "bower_components",
  // Editor and AI agent settings: not the project's code.
  ".claude",
  ".cursor",
  ".vscode",
  ".idea",
  ".husky",
]);

export const ALWAYS_EXCLUDE_FILE_NAMES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
]);

/**
 * `vendor/` holds third-party code only at the repository root (Composer, Go,
 * Rails) or inside a static-files folder (`app/assets/vendor/`). Elsewhere it
 * is a domain word (`src/modules/vendor/` in a marketplace) and stays.
 */
export const VENDOR_DIR_NAME = "vendor";
export const STATIC_DIR_NAMES = new Set(["assets", "public", "static"]);

/** Minified bundles (`jquery.min.js`): third-party or built, never reviewed source. */
export const MINIFIED_FILE_PATTERN = /\.min\.[cm]?js$/;

/**
 * Secret-bearing files: never read, chunked into `code_chunks` or sent to
 * the LLM. Matched case-insensitively against the file's base name.
 */
export const SENSITIVE_FILE_NAMES = new Set([
  ".npmrc",
  ".yarnrc.yml",
  ".netrc",
  ".pypirc",
  ".htpasswd",
  "credentials.json",
  "service-account.json",
  "id_rsa",
  "id_dsa",
  "id_ecdsa",
  "id_ed25519",
]);

export const SENSITIVE_FILE_EXTENSIONS = new Set([
  ".pem",
  ".key",
  ".p12",
  ".pfx",
  ".jks",
  ".keystore",
]);
